"""
Constants for E2E testing framework adoption and migration analysis.
Contains keyword lists used for filtering commits and issues.
"""

MIGRATION_KEYWORDS = [
    "migrate",
    "migrated",
    "migration",
    "replace",
    "replaced",
    "replacing",
    "switch",
    "switched",
    "transition",
    "transitioned",
    "move",
    "moved",
    "drop",
    "dropped",
    "deprecate",
    "deprecated",
    "rewrite",
    "rewrote",
    "reimplement",
    "refactor",
    "refactored",
    "modernize",
    "adopt",
    "selenium",
    "cypress",
    "puppeteer",
    "playwright",
    "convert",
    "unify tests",
    "restructure",
    "unstable",
    "brittle",
    "slow",
    "performance",
    "speed",
    "browser compatibility",
    "modern",
    "outdated",
    "maintenance",
    "complex",
    "simplify",
    "cleanup",
    "consolidate",
    "consistency",
    "cross-browser",
    "headless",
    "debug",
    "troubleshoot",
    "reliability",
    "robust",
    "coverage",
    "visibility",
    "observability"
]

ADOPTION_KEYWORDS = [
    "add test",
    "added test",
    "introduce test",
    "create test",
    "initial test",
    "test setup",
    "first test",
    "add e2e",
    "added e2e",
    "new test suite",
    "added regression test",
    "adoption",
    "selenium",
    "cypress",
    "puppeteer",
    "playwright",
    "browser",
    "UI",
    "GUI",
    "user interface",
    "frontend",
    "bug",
    "prevent",
    "verify",
    "test new feature"
]
